---
extends: default

ignore: |
  config/crd/**
  config/testcrds/**
  charts/**/crds/**
  charts/**/charts/**

rules:
  line-length:
    max: 120
    allow-non-breakable-words: true
  indentation:
    spaces: 2
    indent-sequences: false
    check-multi-line-strings: false
  comments:
    min-spaces-from-content: 1
  document-start: disable
  empty-lines:
    max: 1
    max-start: 0
    max-end: 0
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
