apiVersion: v2
name: zenith-operator
description: >-
  A Helm chart for Kubernetes to install the Zenith Operator and its
  dependencies
type: application
version: 0.2.7
appVersion: 0.2.7
kubeVersion: '>= 1.33.0-0'
home: https://github.com/LucasGois1/zenith-operator
sources:
  - https://github.com/LucasGois1/zenith-operator
maintainers:
  - name: Lucas Sampaio de GÃ³is
    email: lucassampaiodegois1@gmail.com
keywords:
  - serverless
  - functions
  - knative
  - tekton
  - operator
dependencies:
  - name: dapr
    version: 1.14.4
    repository: https://dapr.github.io/helm-charts/
    condition: dapr.enabled
