apiVersion: v2
name: zenith-operator
description: A Helm chart for Kubernetes to install the Zenith Operator and its dependencies
type: application
version: 0.1.0
appVersion: "0.0.1"

dependencies:
  - name: ingress
    version: "0.10.0"
    repository: "https://charts.konghq.com"
    alias: kong
    condition: kong.enabled
  - name: dapr
    version: "1.14.4"
    repository: "https://dapr.github.io/helm-charts/"
    condition: dapr.enabled
